### PR TITLE
issue: 1181835 Enable jenkins verification

### PR DESCRIPTION
**Pull request by igor-ivanov**
Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

### CODE REVIEW

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Review by serglelv — APPROVED** [review]

**Pull request merged**
