### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ChrisCoe**
**Motive:**
Took me a while to set up sockperf, and a README like this would have brought me clarity sooner. I noticed the README.md raw text format was not translated well in "Preview mode" so made changes accordingly. General cleanup as well.

**Changes:**
- Format as intended from raw text 603491c
- Add link to license and add header 29cc544
- Minor changes 8d95272
- Combine readmes to one and formatting 7c8bb7d

**Method Tested:**
Spun up a fresh Ubuntu 16.04 VM and followed commands I inserted in doc to successfully compile sockperf binaries.

### CODE REVIEW

**Review by igor-ivanov — COMMENTED** [review]
Thank you for contribution
You did not remove `readme` from https://github.com/Mellanox/sockperf/blob/sockperf_v2/Makefile.am#L49

In addition I noticed a mistake in readme that does not relate your changes but might be fixed too as
`compile aLic`. Should be `compile sockperf`

**Comment by ChrisCoe** [comment]
@igor-ivanov changes requested added. I was wondering what `aLic` was supposed to stand for, makes sense now

Thanks for reviewing

**Comment by salsal97** [comment]
Thank you for these additions, hope they can be merged soon. I'm facing the same issues you were with the readme.

**Comment by igor-ivanov** [comment]
pushed as https://github.com/Mellanox/sockperf/commit/b3df070d564973c9d6a4a0e143de7703043c5713

**Pull request closed without merging**
