### PR TITLE
issue: 1310745 Coding format

### PR DESCRIPTION
**Pull request by igor-ivanov**
These changes format source code to meet unified coding style and add style verification in jenkins

### CODE REVIEW

**Review by serglelv — APPROVED** [review]

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
pushed as a part of https://github.com/Mellanox/sockperf/pull/109

**Pull request closed without merging**
